stages:
  - build
  - test
  - check
  - deploy
  - coverage

cache:
  paths:
    - packrat/

before_script:
  - make restore_packrat

build:
  stage: build
  tags: 
    - collaudo
  script:
    - R CMD build . --no-build-vignettes --no-manual
  artifacts:
    paths:
      - ./*.tar.gz

test_collaudo:
  stage: test
  tags: 
    - collaudo
  script:
    - make test
  allow_failure: true

test_prod:
  stage: test
  tags: 
    - prod
  script:
    - make test
    

check:
  stage: check
  tags: 
    - collaudo
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check $(ls -1t *.tar.gz | head -n 1) -no-build-vignettes --no-manual --as-cran 
      
coverage:
  stage: coverage
  tags: 
    - collaudo
  script:
    - make coverage
    
deploy:
  stage: deploy
  tags:
    - prod
  script:
    - make install
    
deploy_collaudo:
  stage: deploy
  tags:
    - collaudo
  script:
    - make install
