stages:
  - build
  - test
  - deploy
  - check
  - coverage

build:
  stage: build
  tags: 
    - collaudo
  script:
    - R -e 'devtools::document()'
    - R CMD build . --no-build-vignettes --no-manual

test:
  stage: test
  tags: 
    - collaudo
  script: 
    - R -e 'devtools::test()'
# reports:
#    junit: tests.xml

check:
  stage: check
  tags: 
    - collaudo
  script:
    - R -e 'devtools::document()'
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check $(ls -1t *.tar.gz | head -n 1) -no-build-vignettes --no-manual
  allow_failure: true

deploy:
  stage: deploy
  tags:
    - prod
  script:
    - make install
  allow_failure: false
    
deploy_collaudo:
  stage: deploy
  tags:
    - collaudo
  script:
    - make install
  allow_failure: true


coverage:
  stage: coverage
  tags: 
    - collaudo
  script:
    - make coverage
  allow_failure: true
