# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r_github_packages:
  - jimhester/covr
  - rstudio/packrat

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev tk8.5

after_success:
  - Rscript -e 'covr::codecov(line.exclusions=file.path("packrat", list.files(path="packrat", recursive=T)))'
  