# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

addons:
  apt:
    packages:
       - libxml2-dev

notifications:
  slack:
    rooms:
      - cf0:tjcxGLnksq3MlvPvcPauQ7XO#general

env:
  - GRAFODB_ENV=test

r:
  - release
# this has to be removed as soon as possible (I know it will last forever :( )  
warnings_are_errors: false

pandoc: false

latex: false

repos:
  CRAN: http://cran.rstudio.com

r_github_packages:
  - jimhester/covr

after_success:
  - make test
  - make codecov
  
