version: 2

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: building-on-ci
      VERSION: 3.5.3
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    working_directory: ~/main
    docker:
      - image: giupo/r-dev:3.5.3
    steps:
      - checkout
      - run: apt-get update -yy && apt-get upgrade -yy
      - run: apt-get install -yy libpq-dev unixodbc-dev
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-

      - run:
          name: renv
          command: |
            R -e 'renv::restore()'

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "~/main/GrafoDB/renv"
            - "~/.local/share/renv"
      - run:
          name: check
          command: |
            R -e 'install.packages("devtools")'
            R -e 'devtools::check(cran=FALSE, error_on="error")'

      - store_artifacts:
          path: man/
          destination: man
  test:
    working_directory: ~/main
    docker:
      - image: giupo/r-dev:3.5.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          name: renv
          command: |
            R -e 'renv::restore()'

      - run:
          name: tests
          command: |
            mkdir -p reports
            R -e 'options(testthat.output_file="reports/junit.xml"); devtools::test(reporter="junit")'
          when: always
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

      - run:
          name: coverage
          command: |
             make coverage
  
  build_image:
    executor: docker-publisher
    working_directory: ~/main
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image (latest)
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Build Docker image ( $VERSION )
          command: docker build -t $IMAGE_NAME:$VERSION .
      - run:
          name: Archive Docker image latest
          command: docker save -o image.tar $IMAGE_NAME:latest
      - run:
          name: Archive Docker image $VERSION
          command: docker save -o image-$VERSION.tar $IMAGE_NAME:$VERSION
    - persist_to_workspace:
        root: .
        paths:
          - ./image.tar
          - ./image-$VERSION.tar

  publish:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image latest
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Load archived Docker image $VERSION
          command: docker load -i /tmp/workspace/image-$VERSION.tar
      - run:
          name: Publish Docker Image to Docker Hub latest
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Publish Docker Image to Docker Hub latest $VERSION
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$VERSION
  
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - build_image:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build_image
          filters:
            branches:
              only: master