version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: giupo/r-dev:3.5.3
    steps:
      - checkout
      - run: apt-get update -yy && apt-get upgrade -yy
      - run: apt-get install -yy libpq-dev unixodbc-dev
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-

      - run:
          name: renv
          command: |
            R -e 'renv::restore()'

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "~/main/GrafoDB/renv"
            - "~/.local/share/renv"
      - run:
          name: check
          command: |
            R -e 'install.packages("devtools")'
            R -e 'devtools::check(cran=FALSE, error_on="error")'

      - store_artifacts:
          path: man/
          destination: man
  test:
    working_directory: ~/main
    docker:
      - image: giupo/r-dev:3.5.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          name: renv
          command: |
            R -e 'renv::restore()'

      - run:
          name: tests
          command: |
            mkdir -p reports
            R -e 'options(testthat.output_file="reports/junit.xml"); devtools::test(reporter="junit")'
          when: always
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

      - run:
          name: coverage
          command: |
             make coverage
  
  build_image:
    environment:
      IMAGE_NAME: giupo/GrafoDB
      VERSION: 3.5.3
    working_directory: ~/main
    docker:
      - image: giupo/r-dev:3.5.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image (latest)
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Build Docker image ($VERSION)
          command: docker build -t $IMAGE_NAME:$VERSION .

  publish:
    environment:
      IMAGE_NAME: giupo/GrafoDB
    docker:
      - image: giupo/r-dev:3.5.3
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub latest
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Publish Docker Image to Docker Hub latest $VERSION
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$VERSION
  
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - build_image:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master