// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// convert_data_frame
List convert_data_frame(SEXP dataframe0);
RcppExport SEXP GrafoDB_convert_data_frame(SEXP dataframe0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type dataframe0(dataframe0SEXP);
    __result = Rcpp::wrap(convert_data_frame(dataframe0));
    return __result;
END_RCPP
}
