# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load Nativo
#'
#' @name do_history_nativo
#' @usage do_history_nativo(username, password, hostname, port, dbname, names, tag)
#' @param username username per la connessione
#' @param password password per la connessione
#' @param hostname hostname del database
#' @param port porta di ascolto del server
#' @param dbname nome del db
#' @param names nomi di serie da caricare
#' @param tag tag del database da cui caricare le serie
#' @export
#' @import Rcpp
#' @useDynLib GrafoDB
do_history_nativo <- function(username, password, hostname, port, dbname, names, tag, ordinale) {
    invisible(.Call('GrafoDB_do_history_nativo', PACKAGE = 'GrafoDB', username, password, hostname, port, dbname, names, tag, ordinale))
}

#' Carica Archi nativo
#'
#' @name load_archi
#' @usage load_archi(username, password, hostname, port, dbname, tag)
#' @param username username per la connessione
#' @param password password per la connessione
#' @param hostname hostname del database
#' @param port porta di ascolto del server
#' @param dbname nome del db
#' @param tag tag del database da cui caricare le serie
#' @return una matrice di archi
#' @export
#' @import Rcpp
#' @useDynLib GrafoDB
NULL

load_archi <- function(username, password, hostname, port, dbname, tag) {
    .Call('GrafoDB_load_archi', PACKAGE = 'GrafoDB', username, password, hostname, port, dbname, tag)
}

#' Load Nativo
#'
#' @name load_data
#' @usage load_data(username, password, hostname, port, dbname, names, tag)
#' @param username username per la connessione
#' @param password password per la connessione
#' @param hostname hostname del database
#' @param port porta di ascolto del server
#' @param dbname nome del db
#' @param names nomi di serie da caricare
#' @param tag tag del database da cui caricare le serie
#' @return a list
#' @export
#' @import Rcpp
#' @useDynLib GrafoDB
load_data <- function(username, password, hostname, port, dbname, names, tag) {
    .Call('GrafoDB_load_data', PACKAGE = 'GrafoDB', username, password, hostname, port, dbname, names, tag)
}


#' Save Nativo (non implementato)
#'
#' @name save_data
#' @usage save_data(series, tag)
#' @param series lista di serie da salvare
#' @param tag tag del database da cui caricare le serie
#' @export
#' @import Rcpp
#' @useDynLib GrafoDB

save_data <- function(dati, functions, archi, tag, newtag) {
    invisible(.Call('GrafoDB_save_data', PACKAGE = 'GrafoDB', dati, functions, archi, tag, newtag))
}

