# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' shit full
#'
#' @name load_data
#' @usage load_data(username, password, hostname, port, dbname, names, tag)
#' @param username username per la connessione
#' @param password password per la connessione
#' @param hostname hostname del database
#' @param port porta di ascolto del server
#' @param dbname nome del db
#' @param names nomi di serie da caricare
#' @param tag tag del database da cui caricare le serie
#' @return a list
#' @export
#' @useDynLib testpq
NULL

load_data <- function(username, password, hostname, port, dbname, names, tag) {
    .Call('testpq_load_data', PACKAGE = 'testpq', username, password, hostname, port, dbname, names, tag)
}

