# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converte un dataframe in timeseries
#'
#' Viene usato nella conversione dei dati dal db
#'
#' @name convert_data_frame
#' @usage convert_data_frame(df)
#' @param df data.frame con le serie storiche 
#' @return a List
#' @export
#' @import Rcpp
#' @useDynLib GrafoDB
convert_data_frame <- function(dataframe0) {
    .Call('_GrafoDB_convert_data_frame', PACKAGE = 'GrafoDB', dataframe0)
}

